config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", :sign_out_via => [:get]
  devise_scope :user do
    get "/login", to: "users/sessions#new"
  end

  # Defines the root path route ("/")
  root "static#home"

  # admin
  namespace :admin do
    get "/" => "dashboard#index"

    resources :blocks
    resources :images
    resources :users
    resources :pages
    resources :programs do
      resources :themes do
        resources :topics
      end
    end

    resources :quotations do
      member do
        get "show", defaults: { format: "html" }
        get "show.pdf", to: "quotations#show", defaults: { format: "pdf" }
      end
    end

    # user
    get "profile" => "users#profile", as: :profile
    get "change_password" => "users#change_password", as: :change_password
    patch "update_profile" => "users#update_profile", as: :update_profile
    patch "update_password" => "users#update_password", as: :update_password
  end

  # Public routes
  resources :topics, only: [:show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Errors
  # https://guides.rubyonrails.org/v4.2.0/action_controller_overview.html#custom-errors-page
  match "404", via: :all, to: "errors#not_found", as: :not_found
  match "422", via: :all, to: "errors#unprocessable_entity", as: :unprocessable_entity
  match "500", via: :all, to: "errors#server_error", as: :server_error
  match "offline", via: :all, to: "errors#offline", as: :offline
end

app/models/program.rb
class Program < ApplicationRecord
    belongs_to :user
    has_many :themes, dependent: :destroy
    has_many :visits, as: :visitable, dependent: :destroy
    validates :title, presence: true
    validates :year, numericality: { only_integer: true, greater_than_or_equal_to: 2000, less_than_or_equal_to: Date.today.year + 10 }
    validates :number, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/admin/programs_controller.rb
class Admin::ProgramsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_program, only: %i[ show edit update destroy ]

  layout "admin"

  # GET /programs
  def index
    @programs = Program.all
  end

  # GET /programs/1
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new(user: current_user)
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  def create
    @program = Program.new(program_params)
    @program.user = current_user
    if @program.save
      redirect_to admin_programs_url, notice: "El Programa ha sido creado."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /programs/1
  def update
    if @program.update(program_params)
      redirect_to admin_programs_url, notice: "El Programa ha sido actualizado."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /programs/1
  def destroy
    @program.destroy!
    redirect_to admin_programs_url, notice: "El Programa ha sido eliminado."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def program_params
      params.require(:program).permit(:title, :description, :year, :objective)
    end
end

app/controllers/programs_controller.rb
class Admin::ProgramsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_program, only: %i[ show edit update destroy ]

  layout "admin"

  # GET /programs
  def index
    @programs = Program.all
  end

  # GET /programs/1
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  def create
    @program = Program.new(program_params)

    if @program.save
      redirect_to admin_programs_url, notice: "Program ha sido creado."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /programs/1
  def update
    if @program.update(program_params)
      redirect_to admin_programs_url, notice: "Program ha sido actualizado."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /programs/1
  def destroy
    @program.destroy!
    redirect_to admin_programs_url, notice: "Program ha sido eliminado."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def program_params
      params.require(:program).permit(:name, :description, :year, :school, :url)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/admin/programs/_form.html.erb
<section class="w-full mx-auto">
  <%= form_for [:admin, program], local: true do |f| %>
    <%= render "shared/errors", object: program %>
        
    <div class="flex gap-4">
      <div class="w-2/3">      
        <%= render "components/label", f: f, name: :title, text: t(:title), icon: "fas fa-text" %>
        <%= render "components/input", f: f, input_type: :text_field, name: :title %>
      </div>
      <div class="w-1/3">      
        <%= render "components/label", f: f, name: :year, text: t(:year), icon: "fas fa-calendar" %>
        <%= render "components/input", f: f, input_type: :number_field, name: :year %>
      </div>
    </div>
    
    <div class="w-full">
        <%= render "components/label", f: f, name: :description, text: t(:description), icon: "fas fa-align-left" %>
        <%= render "components/input", f: f, input_type: :text_area, name: :description %>
    </div>

    <div class="w-full">
        <%= render "components/label", f: f, name: :objective, text: t(:objective), icon: "fas fa-align-left" %>
        <%= render "components/input", f: f, input_type: :text_area, name: :objective %>
    </div>
      
    <footer class="w-full flex justify-end sticky bottom-0 bg-black px-4 py-2 mt-2">
      <%= render "components/btn", text: t(:save), button_type: 'submit' %>
    </footer>

  <% end %>
</section>

app/views/admin/programs/edit.html.erb
<% provide(:title, "Editando #{t(:program)}") %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium"><%= "#{t(:editing)} #{t(:program)}" %></h1>
    </div>
  <nav class="my-4 flex gap-4 text-sm">
    <%= link_to admin_programs_path, class: 'btn-xs danger' do %>
      <i class="fa-solid fa-arrow-left pr-1"></i> Regresar
    <% end %>
  </nav>
</header>

<%= render 'form', program: @program %>

app/views/admin/programs/index.html.erb
<% provide(:title, "#{t(:programs)}" ) %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4 w-full">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium"><%= t(:programs) %> <sup>
          <%= Program.all.count %>
        </sup></h1>
  </div>
  <nav class="my-4 flex gap-4 text-sm">
    <%= render "components/link", href: new_admin_program_path, text: "Nuevo Programa", icon: "fa-solid fa-plus" %>
  </nav>
</header>

<section class="my-8 flow-root">
  <table class="w-full">
    <thead class="text-left">
      <tr>
        <th colspan="3">Programa</th>
      </tr>
    </thead>
    <tbody>
      <% @programs.each do |program| %>
        <tr>
          <td>
            <%= link_to edit_admin_program_url(program), class: "" do %>
              <%= program.title %>
            <% end %>
          </td>
          <td class="text-sm py-2 text-center">
            <%= render "components/link", href: admin_program_themes_path(program), text: "#{program.themes.count} Clase#{program.themes.count != 1 ? 's' : ''}", icon: "fa-solid fa-book-open" %>
          </td>
          <td class='text-center'>
            <%= link_to admin_program_path(program), method: :delete, class: "btn danger" , data: {
              confirm: "¿Estás seguro de eliminar este #{t(:program)}?" } do %>
              <i class='fas fa-trash'></i> Eliminar
              <% end %>
          </td>
        </tr>
        <% end %>
    </tbody>
  </table>
</section>

app/views/admin/programs/new.html.erb
<% provide(:title, "Nuevo Programa") %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium"><%= "#{t(:new)} #{t(:program)}" %></h1>
    </div>
  <nav class="my-4 flex gap-4 text-sm">
    <%= link_to admin_programs_path, class: 'btn-xs danger' do %>
      <i class="fa-solid fa-arrow-left pr-1"></i> Regresar
    <% end %>
  </nav>
</header>

<%= render 'form', program: @program %>