config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", :sign_out_via => [:get]
  devise_scope :user do
    get "/login", to: "users/sessions#new"
  end

  # Defines the root path route ("/")
  root "static#home"

  # admin
  namespace :admin do
    get "/" => "dashboard#index"

    resources :blocks
    resources :images
    resources :users
    resources :pages
    resources :programs do
      resources :themes do
        resources :topics
      end
    end

    resources :quotations do
      member do
        get "show", defaults: { format: "html" }
        get "show.pdf", to: "quotations#show", defaults: { format: "pdf" }
      end
    end

    # user
    get "profile" => "users#profile", as: :profile
    get "change_password" => "users#change_password", as: :change_password
    patch "update_profile" => "users#update_profile", as: :update_profile
    patch "update_password" => "users#update_password", as: :update_password
  end

  # Public routes
  resources :topics, only: [:show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Errors
  # https://guides.rubyonrails.org/v4.2.0/action_controller_overview.html#custom-errors-page
  match "404", via: :all, to: "errors#not_found", as: :not_found
  match "422", via: :all, to: "errors#unprocessable_entity", as: :unprocessable_entity
  match "500", via: :all, to: "errors#server_error", as: :server_error
  match "offline", via: :all, to: "errors#offline", as: :offline
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :theme
  has_many :blocks, as: :blockable, dependent: :destroy
  accepts_nested_attributes_for :blocks, allow_destroy: true
  has_many :visits, as: :visitable, dependent: :destroy
  
  CONTENT_TYPES = {
    video_studio: "Video (Studio)",
    screencast: "Screencast",
    pdf_ppt: "PDF PPT",
    quiz: "Quiz",
    tarea_texto: "Tarea - Texto",
    survey: "Survey",
    na: "N/A",
    video_screencast: "Video/Screencast",
    video_grabado: "Video ya grabado"
  }.freeze

  enum content_type: CONTENT_TYPES.keys

  validates :title, presence: true
  validates :content_type, presence: true, inclusion: { in: content_types.keys }
  
  # Scopes
  scope :ordered, -> { order(created_at: :desc) }

  def content_type_text
    CONTENT_TYPES[content_type]
  end
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_program_theme
  before_action :set_topic, only: %i[show edit update destroy]

  layout "admin"

  def index
    @topics = @theme.topics
  end

  def new
    @topic = @theme.topics.build
  end

  def create
    @topic = @theme.topics.build(topic_params)

    if @topic.save
      redirect_to admin_program_theme_topics_path(@program, @theme), notice: "Topic creado con éxito."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "topic_#{@topic.id}",
               layout: "pdf",
               disposition: "inline",
               page_size: "Letter",
               orientation: "Landscape",
               margin: { top: 0, bottom: 0, left: 0, right: 0 }
      end 
    end
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to admin_program_theme_topics_path(@program, @theme), notice: "Topic actualizado con éxito."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @topic.destroy
    redirect_to admin_program_theme_topics_path(@program, @theme), notice: "Topic eliminado con éxito."
  end

  private

  def set_program_theme
    @program = Program.find(params[:program_id])
    @theme = @program.themes.find(params[:theme_id])
  end

  def set_topic
    @topic = @theme.topics.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:theme_id,:number,:title,:estimated_time,:content_type,:objective,:exercises,:homework,:comments,:reference_material,:credits_and_sources, :presentation, blocks_attributes: [:id, :title, :description, :image_id, :block_type, :_destroy])
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show]

  def show
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

end 

app/helpers/topics_helper.rb
module TopicsHelper

    def add_block_to_topic_link(f, association)
		new_object = f.object.send(association).klass.new
		id = new_object.object_id
		fields = f.fields_for(association, new_object) do |builder|
			render("admin/topics/#{association.to_s.singularize}_fields", f: builder, idx: id)
		end
		
		# Sanitize the HTML content
		sanitized_fields = fields
			.gsub(/\s*<!--.*?-->\s*/m, '') # Remove HTML comments
			.gsub(/\s+/, ' ')             # Replace multiple spaces with single space
			.strip                        # Remove leading/trailing whitespace
		
		link_to("Nuevo Bloque", '#', 
			id: "add-topic-block-btn", 
			class: "px-3 py-1.5 text-sm font-semibold text-white focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-yellow-600 ring-light cursor-pointer", 
			data: { 
				id: id, 
				fields: sanitized_fields 
			}
		)
	end

end

app/views/admin/topics/_block_fields.html.erb
<div id="topic-block-<%= idx %>" class="w-full flex gap-2">
    <div class="w-7/12 flex flex-col gap-2">
        <div class="w-full flex gap-2 items-end">
            <div class="w-5/12">
                <%= render "components/label", f: f, name: :title, text: t(:title), icon: "fas fa-text" %>
                <%= render "components/input", f: f, input_type: :text_field, name: :title %>
            </div>
            <div class="w-5/12">
                <%= render "components/label", f: f, name: :block_type, text: t(:block_type), icon: "fas fa-text" %>
                <%= render "components/select", f: f, attr: :block_type, options: Block::BLOCK_TYPES %>
                
            </div>
            <div class="w-2/12">
                <%= f.label :_destroy do %>
                    <div class="button remove-block text-center" data-target="#topic-block-<%= idx %>">
                        <%= f.check_box :_destroy, class: "sr-only" %>
                        <i class="fa fa-trash" aria-hidden="true"></i>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="w-full ">
            <%= render "components/label", f: f, name: :description, text: t(:description), icon: "fas fa-align-left" %>
            <div class="editor-container text-black text-sm">
                <%= render "components/input", f: f, input_type: :text_area, name: :description %>
            </div>
        </div>
    </div>
    <div class="w-5/12 text-center">
        <%= render "img_uploader", f: f, object: f.object.image %>
    </div>
</div>

app/views/admin/topics/_blocks.html.erb
<div class="w-full">
    <header class="w-full flex justify-end py-2">
        <%= add_block_to_topic_link f, :blocks %>
    </header>
    <div class="w-full" id="topic-blocks-container">
        <% idx = 0 %>
        <%= f.fields_for :blocks do |block| %>
            <%= render "admin/topics/block_fields", f: block, idx: idx %>
        <% idx += 1 %>
        <% end %>
    </div>
</div>

app/views/admin/topics/_content.html.erb
<section class="w-full">
    <div class="grid grid-cols-2 gap-4">
        <div class="w-full">
            <%= render "components/label", f: f, name: :objective, text: t(:objective), icon: "fas fa-align-left" %>
            <div class="editor-container text-black text-sm">
                <%= render "components/input", f: f, input_type: :text_area, name: :objective %>
            </div>
        </div>
        <div class="w-full">
            <%= render "components/label", f: f, name: :presentation, text: "Introducción", icon: "fas fa-align-left" %>
            <div class="big-editor editor-container text-black text-sm">
                <%= render "components/input", f: f, input_type: :text_area, name: :presentation %>
            </div>
        </div>
    </div>
    
    <div class="w-full">
        <%= render "components/label", f: f, name: :comments, text: t(:comments), icon: "fas fa-align-left" %>
        <div class="editor-container text-black text-sm">
            <%= render "components/input", f: f, input_type: :text_area, name: :comments %>
        </div>
    </div>
</section>

app/views/admin/topics/_exercises.html.erb
<div class="grid grid-cols-2 gap-4">
    <div class="w-full">
        <%= render "components/label", f: f, name: :exercises, text: t(:exercises), icon: "fas fa-align-left" %>
        <div class="editor-container text-black text-sm">
            <%= render "components/input", f: f, input_type: :text_area, name: :exercises %>
        </div>
    </div>
        
    <div class="w-full">
        <%= render "components/label", f: f, name: :homework, text: t(:homework), icon: "fas fa-align-left" %>
        <div class="editor-container text-black text-sm">
            <%= render "components/input", f: f, input_type: :text_area, name: :homework %>
        </div>
    </div>
</div>

app/views/admin/topics/_form.html.erb
<section class="w-full mx-auto ">
  <%= form_for [:admin, @program, @theme, topic], local: true do |f| %>
    <%= render "shared/errors", object: topic %>
        
    <%= f.hidden_field :theme_id %>

    <header class="border-b border-light/40">
        <div class="sm:flex sm:items-baseline">
          <nav class="-mb-px flex space-x-8 text-xs uppercase">
            <a href="#topic-info"         class="tab-link active">Información</a>
            <a href="#topic-content"      class="tab-link">Contenido</a>
            <a href="#topic-blocks"       class="tab-link">Bloques</a>
            <a href="#topic-exercises"    class="tab-link">Ejercicios</a>
            <a href="#topic-references"   class="tab-link">Referencias</a>
          </nav>
        </div>
      </header>
  
    <div class="tab-content ">
        <div class="tab w-full"        id="topic-info">   <%= render "admin/topics/info",       topic: topic, f: f %>   </div>
        <div class="tab w-full hidden" id="topic-content"><%= render "admin/topics/content",       topic: topic, f: f %></div>
        <div class="tab w-full hidden" id="topic-blocks"> <%= render "admin/topics/blocks",       topic: topic, f: f %></div>
        <div class="tab w-full hidden" id="topic-exercises"> <%= render "admin/topics/exercises",    topic: topic, f: f %></div>
        <div class="tab w-full hidden" id="topic-references"> <%= render "admin/topics/references",    topic: topic, f: f %></div>
    </div>
    
    
    <footer class="w-full text-right sticky left-0 bottom-0 bg-black py-2 px-4 z-30 flex items-center justify-end border-t border-black-800/50">
      <%= render "components/btn", text: t(:save), button_type: 'submit' %>
    </footer>

    <% end %>

</section>

app/views/admin/topics/_img_uploader.html.erb
<!-- 
 container = .uploader-container
  image = container.querySelector('.uploader-image')
  image_id = container.querySelector('.uploader-id') # se almacenará el id de la imagen que returna el servicio de carga. @see: app/services/image_upload_service.rb
 #buttons
  fileInput = container.querySelector('.uploader-input')
  #progress
  progressBar = container.querySelector('.uploader-progress')
 @see: app/javascript/components/uploader.js
-->

<%= f.label :image, class: "uploader-container w-full card group relative overflow-hidden md:hover:unplugged mx-auto cursor-pointer block text-xs", data: { attr: 'image', url: '/admin/images' } do %>
    <%= f.file_field :image, class: "uploader-input sr-only", accept: "image/*" %>
    <!-- 
    * El markup de este parcial es similar a los modelos 'image', 'Image', 'Video', 'OgImage'
    * sólo cambia el 'image_id', en este caso responde al modelo 'image', coincidente con la misma forma
    * repetir la operación de parciales con los demás modelos multimedia
     -->
     <%= f.text_field :image_id, class: "uploader-id sr-only" %>
     <div class="uploader-progress bg-light h-1.5 w-0 left-0 absolute bottom-0"></div>
     <% src = object.present? ? object.file.url(:small) : "/static/not-found.png" %>
    <img src="<%= src %>" data-src="<%= src %>" class="uploader-image opacity-40 md:group-hover:opacity-80 md:group-hover:scale-105 w-full h-auto transition-all aspect-video object-cover object-center">
    <img src="/static/logo.svg" alt="Logo" class="uploader-loader w-12 inline absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2">
    <small class="absolute right-0 top-0 text-right p-4 opacity-60 md:group-hover:opacity-100 transition-opacity normal-case">1920x1080*.PNG</small>
    <small class="block"><span class="uploader-percent text-green"></span> Cover </small>
<% end %>

app/views/admin/topics/_info.html.erb
<div class="flex gap-4">
    <div class="w-8/12">
        <%= render "components/label", f: f, name: :title, text: t(:title), icon: "fas fa-text" %>
        <%= render "components/input", f: f, input_type: :text_field, name: :title %>
    </div>
    
    <div class="w-2/12">
        <%= render "components/label", f: f, name: :estimated_time, text: t(:estimated_time), icon: "fas fa-field" %>
        <%= render "components/input", f: f, input_type: :number_field, name: :estimated_time %>
    </div>
    
    <div class="w-2/12">
        <%= render "components/label", f: f, name: :content_type, text: t(:content_type), icon: "fas fa-text" %>
        <%= render "components/select", f: f, attr: :content_type, options: Topic::CONTENT_TYPES %>
    </div>
</div>

app/views/admin/topics/_references.html.erb
<div class="grid grid-cols-2 gap-4">
    <div class="w-full">
        <%= render "components/label", f: f, name: :reference_material, text: t(:reference_material), icon: "fas fa-align-left" %>
        <div class="editor-container text-black text-sm">
            <%= render "components/input", f: f, input_type: :text_area, name: :reference_material %>
        </div>
    </div>
    <div class="w-full">
        <%= render "components/label", f: f, name: :credits_and_sources, text: t(:credits_and_sources), icon: "fas fa-align-left" %>
        <div class="editor-container text-black text-sm">
            <%= render "components/input", f: f, input_type: :text_area, name: :credits_and_sources %>
        </div>
    </div>
</div>

app/views/admin/topics/edit.html.erb
<% provide(:title, "Editando #{t(:topic)}") %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium"><%= "#{t(:editing)} #{t(:topic)}" %></h1>
    </div>
  <nav class="my-4 flex gap-4 text-sm">
    <%= link_to admin_program_themes_path(@program), class: 'btn-xs danger' do %>
      <i class="fa-solid fa-arrow-left pr-1"></i> Regresar
    <% end %>
  </nav>
</header>

<section class="w-full mx-auto">
  <%= render "form", program: @program, theme: @theme, topic: @topic %>
</section>

app/views/admin/topics/index.html.erb
<% provide(:title, "#{t(:topics)}") %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium">Clases <sup><%= @topics.count %></sup></h1>
  </div>
  <nav class="my-4 flex gap-4 text-sm">
    <%= render "components/link", href: admin_program_themes_path(@program), text: "Regresar", icon: "fa-solid fa-arrow-left" %>
    <%= render "components/link", href: new_admin_program_theme_topic_path(@program, @theme), text: "Tema", icon: "fa-solid fa-plus" %>
    <%= render "components/link", href: new_admin_program_theme_topic_path(@program, @theme, format: :pdf), text: "PDF", icon: "fa-solid fa-file-pdf" %>
  </nav>
</header>

<section class="my-8 flow-root">
  <table class="w-full">
    <thead>
      <tr>
        <th></th>
        <th>Tema</th>
        <th>PDF</th>
        <th>Eliminar</th>
      </tr>
    </thead>
    <tbody>
      <% @topics.order(number: :asc).each do |topic| %>
        <tr>
          <td><%= topic.number %></td>
          <td class=" p-2">
            <%= link_to edit_admin_program_theme_topic_path(@program, @theme, topic), class: "" do %>
              <%= topic.title %>
              <small class="block text-white/60 mt-1"><%= topic.objective.html_safe %></small>
            <% end %>
          </td>
          <td class='text-center text-xs'>
            <%= render "components/link", href: admin_program_theme_topic_path(@program, @theme, topic, format: :pdf), text: "PDF", icon: "fas fa-file-pdf" %>
          </td>
          <td class='text-center text-xs'>
            <%= link_to admin_program_theme_topic_path(@program, @theme, topic), method: :delete, class: "btn danger", data: { confirm: "¿Estás seguro de eliminar este #{t(:topic)}?" } do %>
              <i class='fas fa-trash'></i> Eliminar
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/admin/topics/new.html.erb
<% provide(:title, "Nueva Clase") %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium"><%= "#{t(:new)} #{t(:topic)}" %></h1>
    </div>
  <nav class="my-4 flex gap-4 text-sm">
    <%= render "components/link", href: admin_program_theme_topics_path(@program, @theme), text: "Regresar", icon: "fa-solid fa-arrow-left" %>
  </nav>
</header>

<section class="w-full mx-auto">
  <%= render "form", program: @program, theme: @theme, topic: @topic %>
</section>

app/views/admin/topics/show.html.erb
<% provide(:title, "topic") %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium"><%= "#{t(:detail)} de #{t(:topic)}" %></h1>
    </div>
  <nav class="my-4 flex gap-4 text-sm">
    <%= link_to admin_program_theme_topics_path(program, theme), class: 'btn-xs danger' do %>
      <i class="fa-solid fa-arrow-left pr-1"></i> Regresar
    <% end %>
  </nav>
</header>


<section class="content">
  <!-- Default box -->
  <div class="card card-primary card-outline">
    <header class="card-header">
      <%= link_to edit_admin_topic_url(@topic), class: "btn btn-outline-primary btn-sm" do %>
        <i class="fas fa-pencil-alt"></i> Editar
      <% end -%>
      <%= link_to admin_topic_path(@topic), class: "btn btn-outline-danger btn-sm float-right", method: :delete, data: { confirm: "¿Estás seguro de eliminar este #{t(:topic)}?" } do %>
        <i class="fa-solid fa-trash"></i> Eliminar
      <% end -%>
    </header>
    <div class="card-body">
      <div class="row">
        <div class="col-12">
                      <p>
              <strong>Theme:</strong>
                                <%= @topic.theme_id %>
                          </p>
                      <p>
              <strong>Title:</strong>
                                <%= @topic.title %>
                          </p>
                      <p>
              <strong>Objective:</strong>
                                <%= @topic.objective %>
                          </p>
                      <p>
              <strong>Estimated time:</strong>
                                <%= @topic.estimated_time %>
                          </p>
                      <p>
              <strong>Content type:</strong>
                                <%= @topic.content_type %>
                          </p>
                      <p>
              <strong>Exercises:</strong>
                                <%= @topic.exercises %>
                          </p>
                      <p>
              <strong>Homework:</strong>
                                <%= @topic.homework %>
                          </p>
                      <p>
              <strong>Comments:</strong>
                                <%= @topic.comments %>
                          </p>
                      <p>
              <strong>Reference material:</strong>
                                <%= @topic.reference_material %>
                          </p>
                      <p>
              <strong>Credits and sources:</strong>
                                <%= @topic.credits_and_sources %>
                          </p>
                  </div>
      </div>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</section>

app/views/admin/topics/show.pdf.erb
<div class="page" style="background:#5d41bc;height:100%; text-align:center; color:white;">
    <div class="content-page">
    <%= wicked_pdf_image_tag 'http://localhost:3000/static/ebac_mx_logo-white.png', style: 'width: 200px; margin: 20px auto;' %>
    <h1 class="title">
        <%= @topic.title %>
        <small style="display:block; margin-top: 10px; font-size: 22px;text-transform: uppercase;">IT Starter</small>
    </h1>
    <div class="theme-info">
      <h2><%= @topic.theme.number %> - <%= @topic.theme.title %></h2>
    </div>
  </div>
</div>

<% if @topic.objective.present? %>
    <div class="page">
        <div class="content-page">
            <h2>Objetivo</h2>
            <div class="section">
                <p><small><%= @topic.objective.try(:html_safe) %></small></p>
                <%= @topic.presentation.try(:html_safe) %>
            </div>
        </div>
    </div>
<% end %>

<% if @topic.exercises.present? %>
    <div class="page">
        <div class="content-page">
            <div class="section">
                <h3>Ejercicios</h3>
                <%= @topic.exercises.try(:html_safe) %>
            </div>
        </div>
    </div>
<% end %>

<% if @topic.homework.present? %>
    <div class="page">
        <div class="content-page">
            <div class="section">
                <h3>Tarea</h3>
                <%= @topic.homework.try(:html_safe) %>
            </div>
        </div>
    </div>
<% end %>
        
<% if @topic.comments.present? %>
    <div class="page">
        <div class="content-page">
            <div class="section">
                <h3>Comentarios</h3>
                <%= @topic.comments.try(:html_safe) %>
            </div>
        </div>
    </div>
<% end %>

<% if @topic.reference_material.present? %>
    <div class="page">
        <div class="content-page">
            <div class="section">
                <h3>Material de Referencia</h3>
                <%= @topic.reference_material.try(:html_safe) %>
            </div>
        </div>
    </div>
<% end %>

<% if @topic.credits_and_sources.present? %>
    <div class="page">
        <div class="content-page">
            <div class="section">
                <h3>Créditos y Fuentes</h3>
                <%= @topic.credits_and_sources.try(:html_safe) %>
            </div>
        </div>
    </div> 
<% end %>