config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", :sign_out_via => [:get]
  devise_scope :user do
    get "/login", to: "users/sessions#new"
  end

  # Defines the root path route ("/")
  root "static#home"

  # admin
  namespace :admin do
    get "/" => "dashboard#index"

    resources :blocks
    resources :images
    resources :users
    resources :pages
    resources :programs do
      resources :themes do
        resources :topics
      end
    end

    resources :quotations do
      member do
        get "show", defaults: { format: "html" }
        get "show.pdf", to: "quotations#show", defaults: { format: "pdf" }
      end
    end

    # user
    get "profile" => "users#profile", as: :profile
    get "change_password" => "users#change_password", as: :change_password
    patch "update_profile" => "users#update_profile", as: :update_profile
    patch "update_password" => "users#update_password", as: :update_password
  end

  # Public routes
  resources :topics, only: [:show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Errors
  # https://guides.rubyonrails.org/v4.2.0/action_controller_overview.html#custom-errors-page
  match "404", via: :all, to: "errors#not_found", as: :not_found
  match "422", via: :all, to: "errors#unprocessable_entity", as: :unprocessable_entity
  match "500", via: :all, to: "errors#server_error", as: :server_error
  match "offline", via: :all, to: "errors#offline", as: :offline
end

app/models/image.rb
class Image < ApplicationRecord
  has_many :blocks, dependent: :nullify
  # uploaders
  mount_uploader :file, ImageUploader
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_image, only: %i[ show edit update destroy ]

  layout "admin"

  # GET /images
  def index
    @images = Image.all
  end

  # GET /images/1
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  def create
    @image = Image.create(file: params[:image], processed: false)
    if @image.save
      @image.file.recreate_versions!
      # ProcessImageVersionsJob.perform_later(@image.id) TODO: Implementar background de procesamiento de imágenes
      render json: @image, status: :created
    else
      render json: { errors: @image.errors.full_messages }, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /images/1
  def update
    if @image.update(image_params)
      redirect_to admin_images_url, notice: "Image ha sido actualizado."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /images/1
  def destroy
    @image.assets.delete_all
    @image.destroy
    redirect_to admin_images_url, notice: "Image ha sido eliminado."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:file, :width, :height, :orientation, :processed)
    end

end

app/views/admin/images/_form.html.erb
<section class="w-full mx-auto">
  <%= form_for [:admin, image], local: true do |f| %>
    <%= render "shared/errors", object: image %>
        
    <div class="flex gap-4">
      <div class="w-1/3">      
        <%= render "components/label", f: f, name: :width, text: t(:width), icon: "fas fa-text" %>
        <%= render "components/input", f: f, input_type: :number_field, name: :width %>
      </div>
      <div class="w-1/3">      
        <%= render "components/label", f: f, name: :height, text: t(:height), icon: "fas fa-calendar" %>
        <%= render "components/input", f: f, input_type: :number_field, name: :height %>
      </div>
      <div class="w-1/3">
          <%= render "components/label", f: f, name: :orientation, text: t(:orientation), icon: "fas fa-align-left" %>
          <%= render "components/input", f: f, input_type: :text_field, name: :orientation %>
      </div>
    </div>
    
    <div class="flex flex-col justify-center gap-y-2 w-full">
      <figure class="p-4 border border-dark-800 bg-primary-900/10 rounded-sm shadow-md shadow-dark-800/5 flex flex-col justify-center relative cursor-pointer">
          <%= f.label :file, class: "cursor-pointer opacity-80 aspect-video relative group overflow-hidden" do %>
              <%= image_tag f.object.file.url, id: "image-file", class: "group-hover:scale-105 transition opacity-40 group-hover:opacity-80" %>
              <%= f.file_field :file, class: "sr-only input-img", data: { target: "#image-file" }, accept: "image/*" %>
              <figcaption class='absolute px-2 text-base text-center w-full top-1/2 left-0 text-dark-50 font-bold'>*Máximo: 1920x1080px.png</figcaption>
          <% end %>
      </figure>
    </div>
      
    <footer class="w-full flex justify-end sticky bottom-0 bg-black px-4 py-2 mt-2">
      <%= render "components/btn", text: t(:save), button_type: 'submit' %>
    </footer>

  <% end %>
</section>

app/views/admin/images/edit.html.erb
<% provide(:title, "Editando Imagen") %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium">Editando Imagen</h1>
    </div>
  <nav class="my-4 flex gap-4 text-sm">
    <%= link_to admin_images_path, class: 'btn-xs danger' do %>
      <i class="fa-solid fa-arrow-left pr-1"></i> Regresar
    <% end %>
  </nav>
</header>

<%= render 'form', image: @image %>

app/views/admin/images/index.html.erb
<% provide(:title, "#{t(:images)}" ) %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4 w-full">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium"><%= t(:images) %> <sup>
          <%= Image.all.count %>
        </sup></h1>
  </div>
  <nav class="my-4 flex gap-4 text-sm">
    <%= render "components/link", href: new_admin_image_path, text: "Nueva Imagen", icon: "fa-solid fa-plus" %>
  </nav>
</header>

<section class="my-8 flow-root">
  <table class="w-full">
    <thead class="text-left">
      <tr>
        <th colspan="3">Imagen</th>
      </tr>
    </thead>
    <tbody>
      <% @images.each do |image| %>
        <tr>
          <td>
            <%= link_to edit_admin_image_url(image), class: "" do %>
              <img src="<%= image.file.url %>" alt="" class="w-24 h-auto">
            <% end %>
          </td>
          <td class='text-center'>
            <%= link_to admin_image_path(image), method: :delete, class: "btn danger" , data: {
              confirm: "¿Estás seguro de eliminar esta imagen?" } do %>
              <i class='fas fa-trash'></i> Eliminar
              <% end %>
          </td>
        </tr>
        <% end %>
    </tbody>
  </table>
</section>

app/views/admin/images/new.html.erb
<% provide(:title, "Nuevo Programa") %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium"><%= "#{t(:new)} #{t(:image)}" %></h1>
    </div>
  <nav class="my-4 flex gap-4 text-sm">
    <%= render "components/link", text: "Regresar", href: admin_images_path, icon: "fa-solid fa-arrow-left" %>
  </nav>
</header>

<%= render 'form', image: @image %>

app/views/admin/images/show.html.erb
<% provide(:title, "program" ) %>

  <header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4">
    <div class="sm:flex-auto">
      <h1 class="leading-6 text-xl font-medium">
        <%= "#{t(:detail)} de #{t(:program)}" %>
      </h1>
    </div>
    <nav class="text-sm flex gap-4">
      <%= render "components/link", href: edit_admin_program_url(@program), text: "Regresar", icon: "fa-solid fa-arrow-left" %>
      <%= render "components/link", href: new_admin_program_theme_path(@program), text: "Módulo", icon: "fa-solid fa-plus" %>
    </nav>
  </header>


  <section class="content">
    <!-- Default box -->
    <div class="card card-primary card-outline">
      <header class="card-header flex justify-between gap-4">
        <%= render "components/link", href: edit_admin_program_url(@program), text: "Editar", icon: "fa-solid fa-pencil" %>
        <%= link_to admin_program_path(@program), class: "btn btn-outline-danger btn-sm float-right" , method:
          :delete, data: { confirm: "¿Estás seguro de eliminar este #{t(:program)}?" } do %>
          <i class="fa-solid fa-trash"></i> Eliminar
        <% end %>
      </header>
      <div class="card-body">
        <div class="row">
          <div class="col-12">
            <p>
              <strong>Name:</strong>
              <%= @program.title %>
            </p>
            <p>
              <strong>Description:</strong>
              <%= @program.description %>
            </p>
            <p>
              <strong>Year:</strong>
              <%= @program.year %>
            </p>
          </div>
        </div>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </section>